apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ingressName}}
  namespace: {{tenant}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-application-gateway
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - {{host}}
    secretName: tls-secret
  rules:
  - host: {{host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: syntheticapi
            port:
              number: 80